// src/styles/chartThemes.ts

export const chartThemes = {
  voteSplit: {
    background: '#0B0F1C',
    primary: '#00FFD1',
    secondary: '#007BFF',
    tooltipBg: '#1C2333',
    tooltipText: '#E0F7FA',
    fontSize: 12,
  },
  voteMomentum: {
    background: '#0D0B1E',
    primary: '#FF2E92',
    tooltipBg: '#1F112A',
    tooltipText: '#FFD1F1',
    fontSize: 12,
  },
  campaignIntegrity: {
    background: '#0B1F1A',
    primary: '#00E676',
    tooltipBg: '#102C24',
    tooltipText: '#C8FFE0',
    fontSize: 12,
  },
  voterIntegrity: {
    background: '#1C1C2B',
    primary: '#8B5CF6',
    tooltipBg: '#27273D',
    tooltipText: '#E9D8FD',
    fontSize: 12,
  },
  proximityReach: {
    background: '#111827',
    primary: '#FACC15',
    tooltipBg: '#1F2937',
    tooltipText: '#FEF3C7',
    fontSize: 12,
  },
  voteMap: {
    background: '#000B1E',
    primary: '#60A5FA',
    tooltipBg: '#111B3A',
    tooltipText: '#BFDBFE',
    fontSize: 12,
  },
  votePulse: {
    background: '#0A0A23',
    primary: '#22D3EE',
    tooltipBg: '#1E3A8A',
    tooltipText: '#A5F3FC',
    fontSize: 12,
  },
  voteImpact: {
    background: '#1E1B1B',
    primary: '#FB923C',
    tooltipBg: '#3B2F2F',
    tooltipText: '#FED7AA',
    fontSize: 12,
  },
  ageDistribution: {
    background: '#1F2937',
    primary: '#34D399',
    tooltipBg: '#2D3748',
    tooltipText: '#BBF7D0',
    fontSize: 12,
  },
  genderDistribution: {
    background: '#1A202C',
    primary: '#C084FC',
    tooltipBg: '#2A2E3A',
    tooltipText: '#E9D8FD',
    fontSize: 12,
  },
  voteOriginMap: {
    background: '#000814',
    primary: '#38BDF8',
    tooltipBg: '#0F172A',
    tooltipText: '#E0F2FE',
    fontSize: 12,
  },
  scopeGrid: {
    background: '#161B22',
    primary: '#10B981',
    tooltipBg: '#1F2937',
    tooltipText: '#A7F3D0',
    fontSize: 12,
  },
  campaignReach: {
    background: '#0B0B0B',
    primary: '#EAB308',
    tooltipBg: '#2C2C0C',
    tooltipText: '#FEF9C3',
    fontSize: 12,
  },
  creatorIntegrityMatrix: {
    background: '#1E293B',
    primary: '#F472B6',
    tooltipBg: '#334155',
    tooltipText: '#FCE7F3',
    fontSize: 12,
  },
  campaignIntegritySpread: {
    background: '#0F172A',
    primary: '#7DD3FC',
    tooltipBg: '#1E3A8A',
    tooltipText: '#BAE6FD',
    fontSize: 12,
  },
  communityIntegrityMap: {
    background: '#0C1B1F',
    primary: '#F43F5E',
    tooltipBg: '#1E293B',
    tooltipText: '#FECACA',
    fontSize: 12,
  },
};
